// SPDX-License-Identifier: BUSL-1.1
// Part of: adam · ARK (Agglutinative Reasoning Kernel) · github.com/qazaq-ai/adam
//! **Expanded lexicon** (Phase 12 step 5, 2026-05-29) —
//! frequency-curated additions on top of the original 203-entry
//! base. Every entry's phoneme decomposition was produced by
//! `tools/lexicon_gen` running `cyrillic_to_phonemes(..., true)`
//! on the Cyrillic source, so the v6.3 strict-orthographic
//! «ы» / «і» rule is baked in by construction (no hand-
//! transcription drift).
//!
//! Categories: body, family, animal, food, nature, day, month,
//! place adverb, verb_past, verb_pres, size/weight/age
//! adjectives, abstract / activity nouns.

use crate::{LexEntry, Pos};
use adam_phoneme::Phoneme::*;

pub const EXPANDED: &[LexEntry] = &[
    // ─── Body parts ─────────────────────────────────────────
    LexEntry::new("nb_mas", "мас", &[M, A, S], Pos::Noun, "body"),
    LexEntry::new("nb_bet", "бет", &[B, E, T], Pos::Noun, "body"),
    LexEntry::new("nb_tis", "тіс", &[T, S], Pos::Noun, "body"),
    LexEntry::new("nb_aiyq", "аяқ", &[A, A, Q], Pos::Noun, "body"),
    LexEntry::new("nb_mojyn", "мойын", &[M, O, J, N], Pos::Noun, "body"),
    LexEntry::new("nb_qulaq", "құлақ", &[Q, U, L, A, Q], Pos::Noun, "body"),
    LexEntry::new("nb_murn", "мұрын", &[M, U, R, N], Pos::Noun, "body"),
    LexEntry::new("nb_auyz", "ауыз", &[A, W, Z], Pos::Noun, "body"),
    LexEntry::new("nb_shash", "шаш", &[Sh, A, Sh], Pos::Noun, "body"),
    LexEntry::new("nb_bila", "білек", &[B, L, E, K], Pos::Noun, "body"),
    LexEntry::new("nb_tobe", "төбе", &[T, Oe, B, E], Pos::Noun, "body"),
    LexEntry::new("nb_san2", "сан", &[S, A, N], Pos::Noun, "body"),
    LexEntry::new("nb_belb", "бел", &[B, E, L], Pos::Noun, "body"),
    LexEntry::new("nb_kokrek", "кеуде", &[K, E, W, D, E], Pos::Noun, "body"),
    // ─── Family ─────────────────────────────────────────────
    LexEntry::new("nf_ake", "әке", &[Ae, K, E], Pos::Noun, "family"),
    LexEntry::new("nf_aje", "әже", &[Ae, Zh, E], Pos::Noun, "family"),
    LexEntry::new("nf_baba", "баба", &[B, A, B, A], Pos::Noun, "family"),
    LexEntry::new("nf_apke", "әпке", &[Ae, P, K, E], Pos::Noun, "family"),
    LexEntry::new("nf_ini", "іні", &[N], Pos::Noun, "family"),
    LexEntry::new("nf_aga2", "аға", &[A, Gh, A], Pos::Noun, "family"),
    LexEntry::new("nf_tate", "тәте", &[T, Ae, T, E], Pos::Noun, "family"),
    LexEntry::new("nf_kelin", "келін", &[K, E, L, N], Pos::Noun, "family"),
    LexEntry::new("nf_kuyeu", "күйеу", &[K, Ue, J, E, W], Pos::Noun, "family"),
    LexEntry::new("nf_zhubaj", "жұбай", &[Zh, U, B, A, J], Pos::Noun, "family"),
    // ─── Animals ────────────────────────────────────────────
    LexEntry::new("na_mysyq", "мысық", &[M, S, Q], Pos::Noun, "animal"),
    LexEntry::new("na_jylqy", "жылқы", &[Zh, L, Q], Pos::Noun, "animal"),
    LexEntry::new("na_qoj", "қой", &[Q, O, J], Pos::Noun, "animal"),
    LexEntry::new("na_siyr", "сиыр", &[S, I, R], Pos::Noun, "animal"),
    LexEntry::new("na_tuye", "түйе", &[T, Ue, J, E], Pos::Noun, "animal"),
    LexEntry::new("na_eshki", "ешкі", &[E, Sh, K], Pos::Noun, "animal"),
    LexEntry::new("na_qaz", "қаз", &[Q, A, Z], Pos::Noun, "animal"),
    LexEntry::new("na_tauyq", "тауық", &[T, A, W, Q], Pos::Noun, "animal"),
    LexEntry::new("na_qus", "құс", &[Q, U, S], Pos::Noun, "animal"),
    LexEntry::new("na_balyq", "балық", &[B, A, L, Q], Pos::Noun, "animal"),
    LexEntry::new("na_qasqyr", "қасқыр", &[Q, A, S, Q, R], Pos::Noun, "animal"),
    LexEntry::new(
        "na_kobelek",
        "көбелек",
        &[K, Oe, B, E, L, E, K],
        Pos::Noun,
        "animal",
    ),
    LexEntry::new("na_ari", "ара", &[A, R, A], Pos::Noun, "animal"),
    // ─── Food + drink ───────────────────────────────────────
    LexEntry::new("nfd_sut", "сүт", &[S, Ue, T], Pos::Noun, "food"),
    LexEntry::new("nfd_et", "ет", &[E, T], Pos::Noun, "food"),
    LexEntry::new("nfd_qymyz", "қымыз", &[Q, M, Z], Pos::Noun, "food"),
    LexEntry::new("nfd_shai", "шай", &[Sh, A, J], Pos::Noun, "food"),
    LexEntry::new("nfd_qant", "қант", &[Q, A, N, T], Pos::Noun, "food"),
    LexEntry::new("nfd_tuz", "тұз", &[T, U, Z], Pos::Noun, "food"),
    LexEntry::new("nfd_palau", "палау", &[P, A, L, A, W], Pos::Noun, "food"),
    LexEntry::new("nfd_kespe", "кеспе", &[K, E, S, P, E], Pos::Noun, "food"),
    LexEntry::new("nfd_alma", "алма", &[A, L, M, A], Pos::Noun, "food"),
    LexEntry::new("nfd_qauyn", "қауын", &[Q, A, W, N], Pos::Noun, "food"),
    LexEntry::new("nfd_iremq", "ірімшік", &[R, M, Sh, K], Pos::Noun, "food"),
    // ─── Nature ─────────────────────────────────────────────
    LexEntry::new("nn_teniz", "теңіз", &[T, E, Ng, Z], Pos::Noun, "nature"),
    LexEntry::new("nn_ozen", "өзен", &[Oe, Z, E, N], Pos::Noun, "nature"),
    LexEntry::new("nn_bult", "бұлт", &[B, U, L, T], Pos::Noun, "nature"),
    LexEntry::new("nn_jel", "жел", &[Zh, E, L], Pos::Noun, "nature"),
    LexEntry::new("nn_qar", "қар", &[Q, A, R], Pos::Noun, "nature"),
    LexEntry::new(
        "nn_janbyr",
        "жаңбыр",
        &[Zh, A, Ng, B, R],
        Pos::Noun,
        "nature",
    ),
    LexEntry::new("nn_aua", "ауа", &[A, W, A], Pos::Noun, "nature"),
    LexEntry::new("nn_orman", "орман", &[O, R, M, A, N], Pos::Noun, "nature"),
    LexEntry::new("nn_agash", "ағаш", &[A, Gh, A, Sh], Pos::Noun, "nature"),
    LexEntry::new("nn_shoq", "шоқ", &[Sh, O, Q], Pos::Noun, "nature"),
    // ─── Days of week ───────────────────────────────────────
    LexEntry::new(
        "nd_dujsenbi",
        "дүйсенбі",
        &[D, Ue, J, S, E, N, B],
        Pos::Noun,
        "day",
    ),
    LexEntry::new(
        "nd_seisenbi",
        "сейсенбі",
        &[S, E, J, S, E, N, B],
        Pos::Noun,
        "day",
    ),
    LexEntry::new(
        "nd_sarsenbi",
        "сәрсенбі",
        &[S, Ae, R, S, E, N, B],
        Pos::Noun,
        "day",
    ),
    LexEntry::new(
        "nd_bejsenbi",
        "бейсенбі",
        &[B, E, J, S, E, N, B],
        Pos::Noun,
        "day",
    ),
    LexEntry::new("nd_juma", "жұма", &[Zh, U, M, A], Pos::Noun, "day"),
    LexEntry::new("nd_senbi", "сенбі", &[S, E, N, B], Pos::Noun, "day"),
    LexEntry::new(
        "nd_jeksenbi",
        "жексенбі",
        &[Zh, E, K, S, E, N, B],
        Pos::Noun,
        "day",
    ),
    // ─── Months ─────────────────────────────────────────────
    LexEntry::new(
        "nm_qantar",
        "қаңтар",
        &[Q, A, Ng, T, A, R],
        Pos::Noun,
        "month",
    ),
    LexEntry::new("nm_aqpan", "ақпан", &[A, Q, P, A, N], Pos::Noun, "month"),
    LexEntry::new("nm_nauryz", "наурыз", &[N, A, W, R, Z], Pos::Noun, "month"),
    LexEntry::new("nm_sauir", "сәуір", &[S, Ae, W, R], Pos::Noun, "month"),
    LexEntry::new("nm_mamyr", "мамыр", &[M, A, M, R], Pos::Noun, "month"),
    LexEntry::new("nm_mausym", "маусым", &[M, A, W, S, M], Pos::Noun, "month"),
    LexEntry::new("nm_shilde", "шілде", &[Sh, L, D, E], Pos::Noun, "month"),
    LexEntry::new("nm_tamyz", "тамыз", &[T, A, M, Z], Pos::Noun, "month"),
    LexEntry::new(
        "nm_qyrkujek",
        "қыркүйек",
        &[Q, R, K, Ue, J, E, K],
        Pos::Noun,
        "month",
    ),
    LexEntry::new("nm_qazan", "қазан", &[Q, A, Z, A, N], Pos::Noun, "month"),
    LexEntry::new(
        "nm_qarasha",
        "қараша",
        &[Q, A, R, A, Sh, A],
        Pos::Noun,
        "month",
    ),
    LexEntry::new(
        "nm_jeltoqsan",
        "желтоқсан",
        &[Zh, E, L, T, O, Q, S, A, N],
        Pos::Noun,
        "month",
    ),
    // ─── Adverbs of place ───────────────────────────────────
    LexEntry::new("adv_munda", "мұнда", &[M, U, N, D, A], Pos::Adverb, "place"),
    LexEntry::new("adv_sonda", "сонда", &[S, O, N, D, A], Pos::Adverb, "place"),
    LexEntry::new(
        "adv_aldynda",
        "алдында",
        &[A, L, D, N, D, A],
        Pos::Adverb,
        "place",
    ),
    LexEntry::new(
        "adv_artynda",
        "артында",
        &[A, R, T, N, D, A],
        Pos::Adverb,
        "place",
    ),
    LexEntry::new(
        "adv_ishynda",
        "ішінде",
        &[Sh, N, D, E],
        Pos::Adverb,
        "place",
    ),
    LexEntry::new(
        "adv_tomen",
        "төмен",
        &[T, Oe, M, E, N],
        Pos::Adverb,
        "place",
    ),
    LexEntry::new(
        "adv_jogarry",
        "жоғары",
        &[Zh, O, Gh, A, R],
        Pos::Adverb,
        "place",
    ),
    // ─── Verbs (past) ───────────────────────────────────────
    LexEntry::new("vp_keldi", "келді", &[K, E, L, D], Pos::Verb, "verb_past"),
    LexEntry::new("vp_bardy", "барды", &[B, A, R, D], Pos::Verb, "verb_past"),
    LexEntry::new("vp_kordi", "көрді", &[K, Oe, R, D], Pos::Verb, "verb_past"),
    LexEntry::new("vp_bildi", "білді", &[B, L, D], Pos::Verb, "verb_past"),
    LexEntry::new("vp_jazdy", "жазды", &[Zh, A, Z, D], Pos::Verb, "verb_past"),
    LexEntry::new(
        "vp_qarady",
        "қарады",
        &[Q, A, R, A, D],
        Pos::Verb,
        "verb_past",
    ),
    LexEntry::new("vp_oqydy", "оқыды", &[O, Q, D], Pos::Verb, "verb_past"),
    LexEntry::new("vp_otyrdy", "отырды", &[O, T, R, D], Pos::Verb, "verb_past"),
    // ─── Verbs (present) ────────────────────────────────────
    LexEntry::new(
        "vpres_keledi",
        "келеді",
        &[K, E, L, E, D],
        Pos::Verb,
        "verb_pres",
    ),
    LexEntry::new(
        "vpres_baradi",
        "барады",
        &[B, A, R, A, D],
        Pos::Verb,
        "verb_pres",
    ),
    LexEntry::new(
        "vpres_koredi",
        "көреді",
        &[K, Oe, R, E, D],
        Pos::Verb,
        "verb_pres",
    ),
    LexEntry::new(
        "vpres_biledi",
        "біледі",
        &[B, L, E, D],
        Pos::Verb,
        "verb_pres",
    ),
    LexEntry::new(
        "vpres_jazadi",
        "жазады",
        &[Zh, A, Z, A, D],
        Pos::Verb,
        "verb_pres",
    ),
    // ─── Adjectives ─────────────────────────────────────────
    LexEntry::new("adj_uzyn", "ұзын", &[U, Z, N], Pos::Adjective, "size"),
    LexEntry::new("adj_qysqa", "қысқа", &[Q, S, Q, A], Pos::Adjective, "size"),
    LexEntry::new("adj_biik", "биік", &[B, I, K], Pos::Adjective, "size"),
    LexEntry::new(
        "adj_alasa",
        "аласа",
        &[A, L, A, S, A],
        Pos::Adjective,
        "size",
    ),
    LexEntry::new("adj_auyr", "ауыр", &[A, W, R], Pos::Adjective, "weight"),
    LexEntry::new(
        "adj_jenil",
        "жеңіл",
        &[Zh, E, Ng, L],
        Pos::Adjective,
        "weight",
    ),
    LexEntry::new("adj_jas", "жас", &[Zh, A, S], Pos::Adjective, "age"),
    LexEntry::new("adj_kart", "қарт", &[Q, A, R, T], Pos::Adjective, "age"),
    // ─── Abstract / activity ────────────────────────────────
    LexEntry::new("nm_zhumys", "жұмыс", &[Zh, U, M, S], Pos::Noun, "activity"),
    LexEntry::new("nm_din", "дін", &[D, N], Pos::Noun, "abstract"),
    LexEntry::new("nm_orta", "орта", &[O, R, T, A], Pos::Noun, "abstract"),
    LexEntry::new("nm_alem", "әлем", &[Ae, L, E, M], Pos::Noun, "abstract"),
];
